# Users API 

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "fullName" : "Shubik Bhatt 2",
    "email" : "bhattshubik@gmail.com",
    "username" : "shubikbhatt2",
    "password" : "0090909"
}

###

GET http://localhost:3000/api/v1/users

###

GET http://localhost:3000/api/v1/users/2

###

PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
    "fullName" : "Prashrijan Shrestha",
    "email": "prashrijanshrestha@gmail.com",
    "userName": "prashrijanshrestha",
    "password": "565678"
}

###

PATCH http://localhost:3000/api/v1/users/3?email=ramdhimal@gmail.com

###

DELETE http://localhost:3000/api/v1/users/5
